<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1><?php echo $this->translate("An error occurred") ?></h1>
      <h2><?php echo $this->message ?></h2>
      <?php if(isset($this->exception)){ ?>
      <h3><?php echo $this->translate("Exception information") ?>:</h3>
      <p><b><?php echo $this->translate("Message") ?>:</b> <?php echo $this->exception->getMessage() ?></p>
      <h3><?php echo $this->translate("Stack trace") ?>:</h3>
      <pre><?php echo $this->exception->getTraceAsString() ?>
      </pre>
      <h3><?php echo $this->translate("Request Parameters") ?>:</h3>
      <pre><?php echo var_export($this->request->getParams(), true) ?>
      </pre>
      <?php } ?>
    </div>
  </div>
</div>
